import google.auth
import google.colab.auth
import sqlite3
import json
import os
import shutil
from cardinal_glue.auth.core import Auth, InvalidAuthInfo

def _convert_db_to_json(db_path, db_name, json_path, json_name):
    """
    Attempt to convert a Google credentials DB file to a JSON credentials file.

    Parameters
    __________
    db_path: string
        The path to the input DB file.
    db_name: string
        The name of the input DB file.
    json_path: string
        The path to the output JSON file.
    json_name: string
        The name of the output JSON file.

    Returns
    _______
    bool
        Indication of whether a JSON credentials file was successfully created.
    """
    try:
        db = sqlite3.connect(os.path.join(db_path, db_name))
        c = db.cursor()
        cred_list = list(c.execute('SELECT * FROM credentials;'))
        with open(os.path.join(json_path,json_name), 'w') as f:
            f.write(cred_list[0][1])
        # print(f'DB file successfully converted to credentials and saved at {json_path}.')
        return True
    except Exception as e:
        print(f"An error occurred: {e}")
        return False


class GoogleAuth(Auth):    
    """
    A class representing authentication with Google.
    Extends the Auth class.

    Attributes
    __________
    __GOOGLE_AUTH_JSON_NAME: string
        The name of the JSON file containing 
    __GCLOUD_AUTH_DEFAULT_PATH: string
        The operating system-specific location in which 'gcloud auth login' stores the Google credentials DB file.
    __GCLOUD_DB_DEFAULT_NAME: string
        The name of the DB file generated by 'gcloud auth login'.
    __GCLOUD_AUTH_DB_PATH: string
        The path to the DB file generated by 'gcloud auth login'.
    """

    __GOOGLE_AUTH_JSON_NAME = 'google_application_credentials.json'
    __GCLOUD_AUTH_DEFAULT_PATH = None
    __GCLOUD_DB_DEFAULT_NAME = 'credentials.db'
    __GCLOUD_AUTH_DB_PATH = None

    def __init__(self, auth_path=None, auto_auth=True):
        """
        The constructor for the GoogleAuth class.

        Parameters
        __________
        auth_path : string
            A custom path to search for Google authentication files.
        auto_auth : bool
            User choice as whether to automatically attempt authentication with Google while instantiating the object.
        """
        super().__init__()
        if auth_path:
            self.set_auth_directory(auth_path)        
        os.environ['CLOUDSDK_CONFIG'] = self._AUTH_PATH
        os.environ['USE_AUTH_EPHEM'] = '0'
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.join(self._AUTH_PATH, self.__GOOGLE_AUTH_JSON_NAME)
        if os.getenv("COLAB_RELEASE_TAG"):
            self.__GCLOUD_AUTH_DEFAULT_PATH = '/content/.config/'
        if not self.__GCLOUD_AUTH_DEFAULT_PATH:
            self.__GCLOUD_AUTH_DEFAULT_PATH = os.path.join(self._CONFIG_PATH,'gcloud')      
        self.__GCLOUD_AUTH_DB_PATH = os.path.join(self.__GCLOUD_AUTH_DEFAULT_PATH, self.__GCLOUD_DB_DEFAULT_NAME)
        if auto_auth:
            self.authenticate()
            self.prepare_gdrivefs_auth()

    def authenticate(self):
        """
        Attempt to authenticate with Google.
        
        """
        credentials = None
        if self.__google_application_credentials_exist():
            credentials,_ = google.auth.default()
            self.credentials = credentials
        else:
            raise InvalidAuthInfo('Unable to generate credentials. Please ensure that a valid Google credentials file exists.') 

    def __google_application_credentials_exist(self):
        """
        Find existing Google application credentials.

        Returns
        _______
        bool
            Indicates whether a Google credentials JSON file exists.
        """
        if os.getenv('GOOGLE_APPLICATION_CREDENTIALS'):
            return True
        elif self.__google_credentials_db_exists():
            return _convert_db_to_json(self._AUTH_PATH, self.__GCLOUD_DB_DEFAULT_NAME, self._AUTH_PATH, self.__GOOGLE_AUTH_JSON_NAME)

    def __google_credentials_db_exists(self):
        """
        Find existing Google credentials DB file from a previous authentication.

        Returns
        _______
        bool
            Indicates whether a Google credentials DB file exists.
        """
        if os.path.exists(self.__GCLOUD_AUTH_DB_PATH):
            shutil.move(self.__GCLOUD_AUTH_DB_PATH, os.path.join(self._AUTH_PATH, self.__GCLOUD_DB_DEFAULT_NAME))
            # print("\nAn existing Google DB file has been found from a previous 'gcloud auth login' call.\n")
            # print(f"This DB file has been moved to {self._AUTH_PATH}.\n")
            return true
        elif os.getenv("COLAB_RELEASE_TAG"):
            google.colab.auth._gcloud_login()
            shutil.move(self.__GCLOUD_AUTH_DB_PATH, os.path.join(self._AUTH_PATH, self.__GCLOUD_DB_DEFAULT_NAME))
            return true

    def specify_google_credentials_file(self, file_path):
        """
        Allow the user to point to an existing DB or JSON credentials file at a path of their choosing.

        Paramters
        _________
        file_path : string
            The path to the credentials file.
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError('Please specify a valid path.')
        valid_type = {'.json','.db'}
        split_tup = os.path.splitext(file_path)
        file_type = split_tup[1]
        if file_type not in valid_type:
            raise ValueError('Please ensure that the credentials files is either a JSON or DB file.')
        if file_type == '.json':
            json_exists = True
            os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = file_path
            print(f'The path to the Google credentials file has been set to {file_path}.')
        elif file_type == '.db':
            if _convert_db_to_json(self._AUTH_PATH, self.__GCLOUD_DB_DEFAULT_NAME, self._AUTH_PATH, self.__GOOGLE_AUTH_JSON_NAME):
                print(f'A Google credentials file has been saved to {os.path.join(self._AUTH_PATH, self.__GOOGLE_AUTH_JSON_NAME)}.')
                        
    def prepare_gdrivefs_auth(self):
        """
        Prepare Google auth files for use with the pydata_google_auth package (used for authentication in the gdrivefs package)
        """
        pydata_path = os.path.join(self._CONFIG_PATH, 'pydata')
        os.makedirs(pydata_path, exist_ok=True)
        pydata_auth_path = os.path.join(pydata_path,'pydata_google_credentials.json')
        shutil.copy(os.environ['GOOGLE_APPLICATION_CREDENTIALS'], pydata_auth_path)